# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180531_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwuser',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tasks'),
        ),
    ]
