# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180531_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='name',
        ),
    ]
