# Generated by Django 2.0.5 on 2018-06-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180531_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwuser',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.Tasks'),
        ),
    ]
