# Generated by Django 2.0.5 on 2018-06-07 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180601_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwuser',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 6, 7, 12, 54, 43, 282986, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.CWUser'),
        ),
    ]
